### ISSUE TITLE
I want to show uiview using sol

### ISSUE THREAD

**Issue by deathquin** [nightwolf-chen/JDCFFPlayer#2]
how to make uiview sdl?

**Comment by nightwolf-chen** [comment]
UIView rendering is not supported by SDL 2.0 officially, if you want to use SDL 2.0 with UIView you have to look into the source code and make some modifications. I know that SDL 1.2 supports UIView rendering , you could check out the FFmpeg official example ffplayer.c in the FFmpeg source. However, a better way to do video rendering is using OpenGL,  kxmovie provides good example check it out here [kxmovie](https://github.com/kolyvan/kxmovie).

update:
I've made a little example with kxmovie render for JDCFFPlayer in branch opengl_texture, you could checkout the example by:
```c
git clone https://github.com/nightwolf-chen/JDCFFPlayer
git checkout opengl_texture
```
Hope this helps you.
